name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      directory: client
      build-command: npm run build
      deploy-only: hosting
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      ENV_FILE: ${{ secrets.CLIENT_ENV }}
