name: Deploy Functions to Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      directory: functions
      build-command: npm run build
      deploy-only: functions
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      ENV_FILE: ${{ secrets.FUNCTIONS_ENV }}
